services:
  - type: web
    name: cadlytics-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -w 2 -k gthread --threads 4 --timeout 120"
    envVars:
      - key: REDIS_URL
        sync: false
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: OUTPUT_FOLDER
        value: /tmp/converted
      - key: MAX_UPLOAD_MB
        value: "300"
      - key: OMP_NUM_THREADS
        value: "1"
    plan: starter
  - type: worker
    name: cadlytics-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: REDIS_URL
        sync: false
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: OUTPUT_FOLDER
        value: /tmp/converted
      - key: OMP_NUM_THREADS
        value: "1"

databases:
  - name: cadlytics-redis
    plan: free
    ipAllowList: []
